development:
  clients:
    default:
      database: radiosucesso_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: radiosucesso_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        max_retries: 2
        retry_interval: 1
        auto_discover: false
        pool_size: 32
